---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
  - command: /usr/local/bin/octant version
    register: octant_test_output
  - name: octant version
    debug:
      msg: '{{ octant_test_output.stdout }}'
