---
- name: resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: check for install in {{ octant_install_dir }}
  become: yes
  stat:
    path: '{{ octant_install_dir }}'
  changed_when: False
  register: octant_binary
- when: not octant_binary.stat.exists
  block:
    - name: downloading {{ octant_url }}...
      become: yes
      become_user: root
      get_url:
        url: '{{ octant_url }}'
        dest: '{{ octant_tmp_archive }}'
        mode: 0644
        checksum: '{{ octant_checksum }}'
    - name: unarchiving {{ octant_tmp_archive }}
      become: yes
      become_user: root
      unarchive:
        remote_src: yes
        src: '{{ octant_tmp_archive }}'
        dest: '{{ octant_parent_install_dir }}'
        creates: '{{ octant_install_exe }}'
  always:
    - name: rm {{ octant_tmp_archive }}
      become: yes
      become_user: root
      file:
        path: '{{ octant_tmp_archive }}'
        state: absent
- name: linking {{ octant_link }} to {{ octant_install_exe }}
  become: yes
  become_user: root
  file:
    src: '{{ octant_install_exe }}'
    dest: '{{ octant_link }}'
    state: link
